<?xml version="1.0" encoding="utf-8"?><Database Name="QuanLyThuVien" Class="QuanLyThuVienDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=si_nguyen_12345;Initial Catalog=QuanLyThuVien;Integrated Security=True;Trust Server Certificate=True" SettingsObjectName="AssimentGD2.Properties.Settings" SettingsPropertyName="QuanLyThuVienConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ChiTietPhieuMuon" Member="ChiTietPhieuMuons">
    <Type Name="ChiTietPhieuMuon">
      <Column Name="MaPhieu" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaSach" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="PhieuMuon_ChiTietPhieuMuon" Member="PhieuMuon" ThisKey="MaPhieu" OtherKey="MaPhieu" Type="PhieuMuon" IsForeignKey="true" />
      <Association Name="Sach_ChiTietPhieuMuon" Member="Sach" ThisKey="MaSach" OtherKey="MaSach" Type="Sach" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DocGia" Member="DocGias">
    <Type Name="DocGia">
      <Column Name="MaDocGia" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenDocGia" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SoDienThoai" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Association Name="DocGia_PhieuMuon" Member="PhieuMuons" ThisKey="MaDocGia" OtherKey="MaDocGia" Type="PhieuMuon" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="MaNV" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="VaiTro" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TaiKhoan" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="NhanVien_PhieuMuon" Member="PhieuMuons" ThisKey="MaNV" OtherKey="MaNV" Type="PhieuMuon" />
    </Type>
  </Table>
  <Table Name="dbo.NXB" Member="NXBs">
    <Type Name="NXB">
      <Column Name="MaNXB" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenNXB" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="NXB_Sach" Member="Saches" ThisKey="MaNXB" OtherKey="MaNXB" Type="Sach" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuMuon" Member="PhieuMuons">
    <Type Name="PhieuMuon">
      <Column Name="MaPhieu" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaNV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaDocGia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayMuon" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NgayHetHan" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NgayTra" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TrangThaiTra" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="PhieuMuon_ChiTietPhieuMuon" Member="ChiTietPhieuMuons" ThisKey="MaPhieu" OtherKey="MaPhieu" Type="ChiTietPhieuMuon" />
      <Association Name="DocGia_PhieuMuon" Member="DocGia" ThisKey="MaDocGia" OtherKey="MaDocGia" Type="DocGia" IsForeignKey="true" />
      <Association Name="NhanVien_PhieuMuon" Member="NhanVien" ThisKey="MaNV" OtherKey="MaNV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Sach" Member="Saches">
    <Type Name="Sach">
      <Column Name="MaSach" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenSach" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="MaTacGia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaTheLoai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNXB" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NamXuatBan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Sach_ChiTietPhieuMuon" Member="ChiTietPhieuMuons" ThisKey="MaSach" OtherKey="MaSach" Type="ChiTietPhieuMuon" />
      <Association Name="NXB_Sach" Member="NXB" ThisKey="MaNXB" OtherKey="MaNXB" Type="NXB" IsForeignKey="true" />
      <Association Name="TacGia_Sach" Member="TacGia" ThisKey="MaTacGia" OtherKey="MaTacGia" Type="TacGia" IsForeignKey="true" />
      <Association Name="TheLoai_Sach" Member="TheLoai" ThisKey="MaTheLoai" OtherKey="MaTheLoai" Type="TheLoai" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TacGia" Member="TacGias">
    <Type Name="TacGia">
      <Column Name="MaTacGia" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenTacGia" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="QuocTich" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="TacGia_Sach" Member="Saches" ThisKey="MaTacGia" OtherKey="MaTacGia" Type="Sach" />
    </Type>
  </Table>
  <Table Name="dbo.TaiKhoan" Member="TaiKhoans">
    <Type Name="TaiKhoan">
      <Column Name="TenDangNhap" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TheLoai" Member="TheLoais">
    <Type Name="TheLoai">
      <Column Name="MaTheLoai" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenTheLoai" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="TheLoai_Sach" Member="Saches" ThisKey="MaTheLoai" OtherKey="MaTheLoai" Type="Sach" />
    </Type>
  </Table>
</Database>